# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.6'
prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks!
# end
use_frameworks!

target 'meditation_blossom' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessaging'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath] ,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'meditation_blossomTests' do
    inherit! :complete
    # Pods for testing
  end

 # 위젯 타겟 설정 (search paths와 필요한 추가적인 네이티브 라이브러리만 상속/포함)
  target 'MeditationBlossomWidgetExtension' do
    inherit! :search_paths # 이 명령어만으로 충분해야 합니다.
    # 필요한 경우에만 위젯에서 사용하는 RN 라이브러리(e.g., react-native-firebase) Pods를 추가합니다.
  end

  # 푸시 서비스 타겟 설정
  target 'PushNotificationService' do
    inherit! :search_paths
    # ...
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Hermes dSYM 복사를 위한 스크립트
    installer.pods_project.targets.each do |target|
      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        end
      end
    end
  end
end
